services:
  - type: web
    name: sentrix-ai-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt && python -c "from huggingface_hub import hf_hub_download; from tokenizers import Tokenizer; Tokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2'); hf_hub_download('sentence-transformers/all-MiniLM-L6-v2', subfolder='onnx', filename='model.onnx')"
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: "10000"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: OMP_NUM_THREADS
        value: "1"
